export const SIGNED_IN = 'SIGNED_IN';
export const SIGNED_OUT = 'SIGNED_OUT';
export const USER_STATE_CHANGED = 'USER_STATE_CHANGED';

export const SET_ERROR_ALERT = 'SET_ERROR_ALERT';
export const SET_SUCCESS_ALERT = 'SET_SUCCESS_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAILS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
